##############################################################################
# Pipeline annotation header: 1b.TraitClean-v1.3ms_03-27-2025.R
# Manuscript code section(s): 0 / 1
#
# Purpose:
# Clean GNPC sample metadata and SomaScan matrix after the initial database
# extraction; harmonize cognitive scores, diagnoses, sample types, cohort
# maps, and trait outliers.
#
# Principal inputs:
#   - loadedV1_3ms_03-27-25.RData
#   - ANML.BH.7289x1001.RDS
#   - ANML.RM.7289x671.RDS
#   - ANML.UDS.7289x762.RDS
#   - 9b.4cohort.csv
#
# Principal outputs:
#   - BH.map_HDS1.3ms.RDS
#   - RM.map_HDS1.3ms.RDS
#   - UDS.map_HDS1.3ms.RDS
#   - 2.saved.image_trait+human_cleanup_nm+em0_V1_3ms_03-27-25.RData
#
# Step overview:
#   1. Resolve duplicated join columns and normalize APOE codes.
#   2. Convert MoCA and MMSE using the Fasnacht et al. conversion table,
#      adding education adjustment where applicable.
#   3. Remove non-human/unknown analytes from the main protein matrix and
#      ensure measurements are on the log2 RFU scale.
#   4. Create plasma-specific metadata and diagnosis grouping fields,
#      including strict/conflict-aware group labels.
#   5. Clean trait outliers or sentinel values and map external BioHermes,
#      ROSMAP, and UDS sample identifiers back to GNPC sample IDs.
#
# Notes added during manuscript-code alignment:
#   - Original executable code was preserved except for whitespace/encoding cleanup
#     and the explicitly marked non-run archive described below when applicable.
#   - Comments inserted by this pass are prefixed with "ANNOTATION:".
##############################################################################

# ------------------------------------------------------------------------
# ANNOTATION: Load the raw database extraction workspace generated by script
# 1a.
# ------------------------------------------------------------------------
#rootdir="z:/EBD/"
rootdir="c:/Users/edammer_4ceb5ff/Downloads/"
setwd(rootdir)

#load("loadedV1_3.RData") #9 GB all database tables loaded - 'dirty data'
load("loadedV1_3ms_03-27-25.RData")
ls()
#37 variables by ls().



# ------------------------------------------------------------------------
# ANNOTATION: Normalize basic APOE genotype coding and remove duplicate join
# columns inherited from table merges.
# ------------------------------------------------------------------------
## Clean Up Traits
table(numericMeta$APOE)
numericMeta$APOE[numericMeta$APOE==-1]<-NA
numericMeta$APOE[numericMeta$APOE==32]<-23


# Remove duplicate columns for left_join to work
dup_cols <- names(numericMeta)[duplicated(names(numericMeta))]
#contributor_code, visit, sample_type, sample_id

which(colnames(numericMeta)==dup_cols[1])
#1, 8, 14

which(!numericMeta[,1]==numericMeta[,8])
#integer(0)
which(!numericMeta[,1]==numericMeta[,14])
#integer(0)
numericMeta<-numericMeta[,-c(8,14)]

#visit
which(!numericMeta[,2]==numericMeta[,8])
#integer(0)
numericMeta<-numericMeta[,-c(8)]

#sample_type
which(!numericMeta[,3]==numericMeta[,11])
#integer(0)
numericMeta<-numericMeta[,-c(11)]

#sample_id (already used as rownames)
numericMeta<-numericMeta[,-which(grepl("^sample_id",colnames(numericMeta)))]
dim(numericMeta)
#33848    67 in HDSv1.3ms (3-27-25)   previously: 31119   63


## Interconvert MMSE and MoCA per JS Fasnacht et al J Am Geriatrics Soc, 2022

# ------------------------------------------------------------------------
# ANNOTATION: Use the published MoCA/MMSE crosswalk to fill missing
# cognitive scores in either direction.
# ------------------------------------------------------------------------
#  https://agsjournals.onlinelibrary.wiley.com/doi/full/10.1111/jgs.18124
library(dplyr)

# Define the conversion table
conversion_table <- data.frame(
  MoCA = 0:30,
  Equivalent_MMSE = c(0, 2, 7, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                      23, 24, 25, 25, 26, 27, 27, 28, 28, 29, 29, 30, 30, 30, 30),
  MMSE = 0:30,
  Equivalent_MoCA = c(0, 0, 0, 0, 0, 1, 2, 2, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11,
                      12, 13, 14, 15, 16, 17, 19, 20, 21, 23, 25, 28)
)

# Function to convert MoCA to MMSE and vice versa, and replace NA values with conversions
convert_scores <- function(numericMeta) {
  rownames.nm<-rownames(numericMeta)

  # Convert MoCA to MMSE
  numericMeta <- numericMeta %>%
    left_join(conversion_table[, c("MoCA", "Equivalent_MMSE")], by = c("MoCA" = "MoCA")) %>%
    rename(MMSE_Converted = Equivalent_MMSE)

  # Convert MMSE to MoCA
  numericMeta <- numericMeta %>%
    left_join(conversion_table[, c("MMSE", "Equivalent_MoCA")], by = c("MMSE" = "MMSE")) %>%
    rename(MoCA_Converted = Equivalent_MoCA)

# Adjust MoCA_Converted scores only if years_of_education is NOT NA and <= 12
  numericMeta <- numericMeta %>%
    mutate(MoCA_Converted = ifelse(!is.na(years_of_education) & years_of_education <= 12 & !is.na(MoCA_Converted),
                                   MoCA_Converted + 1, MoCA_Converted))

  # Replace NA values in MoCA with converted values where available
  numericMeta <- numericMeta %>%
    mutate(MoCA = ifelse(is.na(MoCA) & !is.na(MoCA_Converted), MoCA_Converted, MoCA),
           MMSE = ifelse(is.na(MMSE) & !is.na(MMSE_Converted), MMSE_Converted, MMSE))

  rownames(numericMeta)<-rownames.nm
  return(numericMeta)
}

#Pull out MMSE and MoCA to distinct trait columns
numericMeta$MMSE<-NA
numericMeta$MMSE[which(numericMeta$cognitive_test_battery=="MMSE")]<-numericMeta$cognitive_test_score[which(numericMeta$cognitive_test_battery=="MMSE")]
numericMeta$MoCA<-NA
numericMeta$MoCA[which(numericMeta$cognitive_test_battery=="MOCA")]<-numericMeta$cognitive_test_score[which(numericMeta$cognitive_test_battery=="MOCA")]

length(which(!is.na(numericMeta$MoCA)))
#7162  previously: 7179
length(which(!is.na(numericMeta$MMSE)))
#17293 previously: 17328


#NumericMeta is data frame with MoCA, MMSE, and years_of_education
numericMeta <- convert_scores(numericMeta)

length(which(!is.na(numericMeta$MoCA)))
#24431  previously: 24481
length(which(!is.na(numericMeta$MMSE)))
#24455  previously: 24507


## Clear data loaded before cleanup (dat, dat2, dat2.unknownAnalytes...)
#dim(dat)

# ------------------------------------------------------------------------
# ANNOTATION: Remove raw intermediate objects and keep only the curated
# metadata/protein matrix objects needed downstream.
# ------------------------------------------------------------------------
#already deleted
dim(numericMeta)
#33848    71  previously: 31119    66
#dim(dat2)
#already deleted
dim(dat2.unknownAnalytes)
#33848   105  previously: 31119   153
#dim(dat3)
#already deleted
dim(dat3.unknownIDs)
#33848   101  previously: 31119   149
dim(exprMat0)
# 7745 33848  previously: 7744 31119
dim(exprMat0.CSF)
# 7745 3233   previously: 7744 3233
dim(exprMat0.plasma)
# 7745 27850  previously: 7744 27878
27850+3233 # =31083  (33848=31083+781+1240+744)
#27878+3233=31111 previous sample count


## Note sample_matrix is -1 for Buffer, Calibrator, QC samples, which do have contributor_code (batch) just like samples.
table(paste0(numericMeta$sample_matrix,".",numericMeta$sample_type))
#-1.Buffer         -1.Calibrator             -1.QC Citrate Plasma.Sample       CSF.Sample    EDTA Plasma.Sample         Serum.Sample
#      781                  1240               744                   638             3233                 23000                 4212

rm(dat)
rm(dat2)
rm(dat2.unknownAnalytes)
rm(dat3)
rm(dat3.unknownIDs)
rm(dup_cols)
rm(genetics.mapt)
rm(genetics.mapt.idx)
rm(genetics.apoe)
rm(genetics.apoe.idx)
rm(genetics.apoe.matched)
rm(genetics.c9)
rm(genetics.c9.idx)
rm(genetics.grn)
rm(genetics.grn.idx)

#remove prior cleanup attempt data
rm(exprMat0.CSF)
rm(exprMat0.plasma)
rm(numericMeta.plasma)
rm(numericMeta.CSF)
rm(numericMeta.clinical)
rm(numericMeta.personMap)
rm(numericMeta.proteomicsMeta)
rm(oldIDs.dat2)
rm(oldIDs.dat3)
rm(sampleIDs.rownames)
rm(total.count)
rm(uniqueIDs)
rm(unknownIDs.idx)
rm(xap.conn)
ls()
# 16 variables remaining


# We will recreate exprMat0 without non-human assays, remove all other large data frames from initial load
analytes.all<-analytes

# ------------------------------------------------------------------------
# ANNOTATION: Restrict the main expression matrix to human SomaScan assays
# and synchronize analyte row names.
# ------------------------------------------------------------------------
exprMat0.all<-exprMat0

table(analytes.all$organism)
#only 7335 "Human"  - our target for exprMat0 (7288 known in 7k platform; but here there are 5k platform specific targets, too)

#analytes$uniqueID has rownames for exprMat0, but they are not in same order
dim(analytes.all)
#7644   16  previously: 7596   37
dim(exprMat0) # still includes nonhuman assays and unknown (custom) seq_id assays
#  7745 33848  previously: 7744 31119
#which(!analytes$uniqueID==rownames(exprMat0))

analytes<-analytes.all[which(analytes.all$organism=="Human"),]
dim(analytes)
#7335   16  previously: 7335   37

exprMat0<-exprMat0.all[match(analytes$uniqueID,rownames(exprMat0.all)),]
dim(exprMat0)
# 7335 33848  previously: 7335 31119


#####################################
## Ensure all data in exprMat is log2

# ------------------------------------------------------------------------
# ANNOTATION: Ensure the expression matrix is consistently represented on
# the log2 RFU scale.
# ------------------------------------------------------------------------

table(numericMeta$sample_type)
## HDS v1.3ms now:
#  Buffer Calibrator       QC     Sample
#     781       1240      744      31083
## previously:
#    -1 Sample
#  4696  26423
table(numericMeta$units)
## HDS v1.3ms now:
#     -1 log2 RFU
#  32692     1156
## previously:
#    -1 log2 RFU
# 29955     1156

range(exprMat0[sample(nrow(exprMat0),100),which(numericMeta$units==-1)],na.rm=T) # RFU
## now:
#     0.4 461639.3
## previously:
# 13.2 363623.3  #partial data -- too big to load all with VM RAM
range(exprMat0[,which(numericMeta$units=="log2 RFU")],na.rm=T) # log2(RFU)
## now:
#  0.02799696 18.67569400
## previously:
#  0.02799696 18.67569400


#too slow:  sapply(which(numericMeta$units==-1), function(x, envir=.GlobalEnv) {exprMat0[,x] <- log2(exprMat0[,x]) })
# reorder samples in both metadata and abundance matrix so that the abundances can be split for log2 transform of the unlogged RFUs
numericMeta<-numericMeta[order(as.character(numericMeta$units)),]
which(is.na(numericMeta$sample_matrix))
## now: integer(0)
which(is.na(numericMeta$units))
## now: integer(0)
## previously: 31112 31113 31114 31115 31116 31117 31118 31119 in both cases -- remove these unknown sample matrix types.

#numericMeta.all <- numericMeta
#previously:  numericMeta<-numericMeta.all[which(!is.na(numericMeta.all$sample_matrix)),]  #removes 8 samples

exprMat0<-exprMat0[,match(rownames(numericMeta),colnames(exprMat0))]
exprMat.unlogSubset<-exprMat0[,which(as.character(numericMeta$units)=="-1")]
exprMat.log2Subset<-exprMat0[,which(numericMeta$units=="log2 RFU")]
exprMat.log2All<-cbind(log2(exprMat.unlogSubset),exprMat.log2Subset)
head(rownames(exprMat.log2All))
head(colnames(exprMat.log2All))

range(exprMat.log2All[sample(nrow(exprMat.log2All),100),which(numericMeta$units==-1)],na.rm=T) # now log2(RFU)
## currently HDS v1.3ms:
# 2.867896 19.513692
## previously:
# -0.7369656 18.9579661

exprMat0<-exprMat.log2All
colnames(numericMeta)[which(colnames(numericMeta)=="units")]<-"original_units"
numericMeta$units="log2 RFU"
numericMeta$original_units[which(numericMeta$original_units==-1)]<-"RFU"

rm(exprMat.log2All)


############################################################
## Extended trait cleanup moved here from later in pipeline.

# ------------------------------------------------------------------------
# ANNOTATION: Move extended trait cleanup into this script so downstream
# analyses start from a single curated metadata object.
# ------------------------------------------------------------------------

## Batch for Tampor from Site
numericMeta$Batch<-numericMeta$contributor_code
which(apply(exprMat0,1,function(x) length(which(is.na(x))))==7335)
#named integer(0) # no rows are all NA now (1 was before, even rowname was NA)
dim(exprMat0)
#7335 33848  previously: 27878 (plasma only)
#exprMat0<-exprMat0[which(!is.na(rownames(exprMat0))),]
#dim(exprMat0)


## 2 Races (caucasian, 5; Afr Am, 2)
numericMeta$raceAA <- NA
numericMeta$raceAA[numericMeta$race==2]<-1
numericMeta$raceAA[numericMeta$race==5]<-0


## Check Calibrator MDS: do they separate into Plasma and CSF clusters?
cal.plotMDS<-limma::plotMDS(exprMat0[,which(numericMeta$sample_type=="Calibrator")], labels=numericMeta$contributor_code[numericMeta$sample_type=="Calibrator"], pch=16, cex=1.3, var.explained=TRUE)
table(numericMeta$contributor_code[numericMeta$sample_type=="Calibrator"][which(cal.plotMDS$x<2)])
table(numericMeta$contributor_code[numericMeta$sample_type=="Calibrator"][which(cal.plotMDS$x>=2)])
# 2 distinct clusters; ABCDEFILMNPQRSTVW on left, NQT on right;
# J(dual plasma/CSF), O (CSF), and GHK (plasma) missing calibrators altogether!

table(numericMeta$sample_matrix[which(numericMeta$sample_type=="Calibrator")][which(cal.plotMDS$x<2)])   # blood
#  -1
#1115

table(numericMeta$sample_matrix[which(numericMeta$sample_type=="Calibrator")][which(cal.plotMDS$x>=2)])  # CSF
# -1
#125

numericMeta$sample_matrix[which(numericMeta$sample_type=="Calibrator")][which(cal.plotMDS$x>=2)] <- "CSF"
numericMeta$sample_matrix[which(numericMeta$sample_type=="Calibrator")][which(cal.plotMDS$x<2)] <- "Plasma"


numericMeta.all <- numericMeta

numericMeta.blood <- numericMeta[which(numericMeta$sample_matrix=="Plasma" | numericMeta$sample_matrix=="EDTA Plasma" | numericMeta$sample_matrix=="Citrate Plasma" | numericMeta$sample_matrix=="Serum"),]
numericMeta.CSF <- numericMeta[which(numericMeta$sample_matrix=="CSF"),]

dim(numericMeta.blood)
#28965    74
dim(numericMeta.CSF)
# 3358   74


## PLASMA specific
###############################################################################################################################################
#binary independent traits for ad, recruited_control (as defined in GNPClookup table) require a new strict Group (diagnosis) column definition:

table(paste0(numericMeta.blood$ad,".",numericMeta.blood$recruited_control))

# ------------------------------------------------------------------------
# ANNOTATION: Build plasma-specific diagnosis and sample metadata used for
# first-pass plasma analyses.
# ------------------------------------------------------------------------
## now:
# 0.0   0.1   0.2  0.NA   1.0   1.2  1.NA  NA.0  NA.2 NA.NA    - #2=pending status, 1 YES, 0 NO (-1 -> NA)
#4076  1156  8180  2121  1280  2771   168  5376  2068  1769
## previously:
# 0.0   0.1   0.2   1.0   1.2  NA.0  NA.2 NA.NA    - #2=pending status, 1 YES, 0 NO (-1 -> NA)
#4088  1156  8132  1282  2776  1165  2070  2899    # now, without site U
#4088  1156  8132  1282  2776  5380  2070  2899    # previously, with site U

numericMeta.blood$Group.AD.CT<-NA
numericMeta.blood$Group.AD.CT[which(paste0(numericMeta.blood$ad,".",numericMeta.blood$recruited_control)=="1.0")]<-"AD"
numericMeta.blood$Group.AD.CT[which(paste0(numericMeta.blood$ad,".",numericMeta.blood$recruited_control)=="0.1")]<-"CT"
table(numericMeta.blood$Group.AD.CT)
#  AD   CT
#1280 1156  now
#1282 1156  previously

numericMeta.blood$Group.MCI.CT<-NA
numericMeta.blood$Group.MCI.CT[which(paste0(numericMeta.blood$mci_sci,".",numericMeta.blood$recruited_control)=="1.0")]<-"MCI"
numericMeta.blood$Group.MCI.CT[which(paste0(numericMeta.blood$mci_sci,".",numericMeta.blood$recruited_control)=="0.1")]<-"CT"
table(numericMeta.blood$Group.MCI.CT)
#  CT  MCI
#1054 1935  now
#1054 1936  previously

numericMeta.blood$Group.FTD.CT<-NA
numericMeta.blood$Group.FTD.CT[which(paste0(numericMeta.blood$ftd,".",numericMeta.blood$recruited_control)=="1.0")]<-"FTD"
numericMeta.blood$Group.FTD.CT[which(paste0(numericMeta.blood$ftd,".",numericMeta.blood$recruited_control)=="0.1")]<-"CT"
table(numericMeta.blood$Group.FTD.CT)
#  CT  FTD
#1156   86  now
#1156   86  previously

numericMeta.blood$Group.PD.CT<-NA
numericMeta.blood$Group.PD.CT[which(paste0(numericMeta.blood$pd,".",numericMeta.blood$recruited_control)=="1.0")]<-"PD"
numericMeta.blood$Group.PD.CT[which(paste0(numericMeta.blood$pd,".",numericMeta.blood$recruited_control)=="0.1")]<-"CT"
table(numericMeta.blood$Group.PD.CT)
#  CT   PD
#1156 4889   now
#1156  678   # previously, with site U: 4893 PD

numericMeta.blood$Group.ALS.CT<-NA
numericMeta.blood$Group.ALS.CT[which(paste0(numericMeta.blood$als,".",numericMeta.blood$recruited_control)=="1.0")]<-"ALS"
numericMeta.blood$Group.ALS.CT[which(paste0(numericMeta.blood$als,".",numericMeta.blood$recruited_control)=="0.1")]<-"CT"
table(numericMeta.blood$Group.ALS.CT)
# ALS   CT
# 190 1156

#  Concatenate disease annotations in a new data frame column "numericMeta.blood$Group", checking separate columns of the data frame numericMeta.blood when more than one
# of the following columns have a value of "AD", "MCI", "FTD", "PD", and/or "ALS", and none of the columns have a value of "CT" in that row for any of these named columns of numericMeta.blood:
# "Group.AD.CT", "Group.MCI.CT", "Group.FTD.CT", "Group.PD.CT", and "Group.ALS.CT".  Further, if only one disease annotation is found, set the Group column value for that row to the one disease annotation.
# Finally, if only "CT" is found in the checked columns, set the Group column value for that row to "CT".
cols <- c("Group.AD.CT", "Group.MCI.CT", "Group.FTD.CT", "Group.PD.CT", "Group.ALS.CT")  #  vector of colnames to check

# ------------------------------------------------------------------------
# ANNOTATION: Create a strict multivariate diagnostic group variable from
# AD/MCI/FTD/PD/ALS/control indicators.
# ------------------------------------------------------------------------
numericMeta.blood$Group <- apply(numericMeta.blood[, cols], 1, function(x) {
  # Remove NA values
  x <- na.omit(x)

  # If no values, return NA
  if (length(x) == 0) return(NA)

  # If all values are "CT", then set Group to "CT"
  if (all(x == "CT")) return("CT")

  # Otherwise, remove any "CT" values and use the remaining disease annotations
  #x <- x[x != "CT"]

  # Get the unique annotations (should be one or more of: "AD", "MCI", "FTD", "PD", "ALS")
  x <- unique(x)

  # If there's only one annotation, return it; if more than one, concatenate them.
  if (length(x) == 1) {
    return(x)
  } else {
    return(paste(x, collapse = "."))
  }
})
table(numericMeta.blood$Group)
#       AD    AD.FTD     AD.MCI AD.MCI.PD    AD.PD      CT      FTD   FTD.PD      MCI   MCI.ALS   MCI.FTD    MCI.PD      PD                  PD
#now:
#     1011         7        236         4       22    1156       65        1     1425       190        13        67    4795
#previously:
#     1012         7        237         4       22    1156       65        1     1425       190        13        67     584   # previously 4799

numericMeta.blood$GroupMulti<-numericMeta.blood$Group
numericMeta.blood$Group[numericMeta.blood$GroupMulti=="AD.FTD"]<-NA
numericMeta.blood$Group[numericMeta.blood$GroupMulti=="AD.MCI"]<-"AD"
numericMeta.blood$Group[numericMeta.blood$GroupMulti=="AD.MCI.PD"]<-NA
numericMeta.blood$Group[numericMeta.blood$GroupMulti=="AD.PD"]<-NA
numericMeta.blood$Group[numericMeta.blood$GroupMulti=="FTD.PD"]<-NA
numericMeta.blood$Group[numericMeta.blood$GroupMulti=="MCI.ALS"]<-"ALS"
numericMeta.blood$Group[numericMeta.blood$GroupMulti=="MCI.FTD"]<-"FTD"
numericMeta.blood$Group[numericMeta.blood$GroupMulti=="MCI.PD"]<-"PD"

table(numericMeta.blood$Group)
#  AD  ALS   CT  FTD  MCI   PD
#1247  190 1156   78 1425 4862  # current
#1249  190 1156   78 1425  651  # previously with site U: PD: 4866


###################################################################
## Clean Outliers/Typos in traits used for correlation

numericMeta.blood.dirty<-numericMeta.blood

# Traits to clean: "years_of_education","height_cm","weight_kg","resting_heart_rate_pulse","systolic_blood_pressure_sitting","diastolic_blood_pressure_sitting"

# ------------------------------------------------------------------------
# ANNOTATION: Set implausible trait values and sentinel codes to NA after
# inspecting ranges/histograms.
# ------------------------------------------------------------------------
# (OK) "age_at_visit", "sex", "raceAA", "bmi", "cdr"

range(numericMeta.blood$height_cm,na.rm=T)
#117 203  now
#  0 226  previously
hist(numericMeta.blood$height_cm)
#numericMeta.blood$height_cm[numericMeta.blood.dirty$height_cm<100]<-NA

range(numericMeta.blood$years_of_education,na.rm=T)
#  0 36  now
#  0 58 previously
#numericMeta.blood$years_of_education[numericMeta.blood.dirty$years_of_education>35]<-NA

range(numericMeta.blood$weight_kg,na.rm=T)
# 23.6 195.0  now
#numericMeta.blood$weight_kg[numericMeta.blood.dirty$weight_kg>400]<-NA
#numericMeta.blood$weight_kg[numericMeta.blood.dirty$weight_kg==0]<-NA
#range(numericMeta.blood$weight_kg,na.rm=T)
# 23.6 188.7  previously

range(numericMeta.blood$bmi,na.rm=T)
#   8.7 68.0   now
#   8.7 174.3  previously
hist(numericMeta.blood$bmi)
#numericMeta.blood$bmi[numericMeta.blood.dirty$bmi>100]<-NA
#range(numericMeta.blood$bmi,na.rm=T)
##   8.7 79.6

range(numericMeta.blood$resting_heart_rate_pulse,na.rm=T)
#  11 153  now
#  11 999  previously
#numericMeta.blood$resting_heart_rate_pulse[numericMeta.blood.dirty$resting_heart_rate_pulse>800]<-NA
##numericMeta.blood$resting_heart_rate_pulse[numericMeta.blood.dirty$resting_heart_rate_pulse==0]<-NA
#range(numericMeta.blood$resting_heart_rate_pulse,na.rm=T)
##  11 153
hist(numericMeta.blood$resting_heart_rate_pulse,breaks=20)
#numericMeta.blood$resting_heart_rate_pulse[numericMeta.blood.dirty$resting_heart_rate_pulse>150]<-NA
#numericMeta.blood$resting_heart_rate_pulse[numericMeta.blood.dirty$resting_heart_rate_pulse<20]<-NA
range(numericMeta.blood$resting_heart_rate_pulse,na.rm=T)
#  11 153  now
#  20 139  previously

range(numericMeta.blood$systolic_blood_pressure_sitting,na.rm=T)
#  12 230  now
#  12 999  previously
#numericMeta.blood$systolic_blood_pressure_sitting[numericMeta.blood.dirty$systolic_blood_pressure_sitting>800]<-NA
#numericMeta.blood$systolic_blood_pressure_sitting[numericMeta.blood.dirty$systolic_blood_pressure_sitting==0]<-NA
#range(numericMeta.blood$systolic_blood_pressure_sitting,na.rm=T)
##  12 230
hist(numericMeta.blood$systolic_blood_pressure_sitting,breaks=40)
numericMeta.blood$systolic_blood_pressure_sitting[numericMeta.blood.dirty$systolic_blood_pressure_sitting<50]<-NA
range(numericMeta.blood$systolic_blood_pressure_sitting,na.rm=T)
#  52 230  now
#  60 230  previously

range(numericMeta.blood$diastolic_blood_pressure_sitting,na.rm=T)
#  33 148  now
#  33 999  previously
#numericMeta.blood$diastolic_blood_pressure_sitting[numericMeta.blood.dirty$diastolic_blood_pressure_sitting>800]<-NA
#numericMeta.blood$diastolic_blood_pressure_sitting[numericMeta.blood.dirty$diastolic_blood_pressure_sitting==0]<-NA
#range(numericMeta.blood$diastolic_blood_pressure_sitting,na.rm=T)
##  33 148
hist(numericMeta.blood$diastolic_blood_pressure_sitting)
#numericMeta.blood$diastolic_blood_pressure_sitting[numericMeta.blood.dirty$diastolic_blood_pressure_sitting>150]<-NA


# More Traits to clean:  "alcohol_hx","total_years_smoked","tia","tbi","mi","depression","anxiety". "APOE4.Dose"
# (OK) "cdr","MMSE","MoCA","visit","sequential_visit_number","C9Orf72","GRN","MAPT",
# (OK, used indirectly; see below):  "recruited_control","ad","ftd","pd","als","mci_sci"

table(numericMeta.blood$alcohol_hx)  # 0/1/2/3: Never/Current/Previous/Never_or_Previous
#   0    1    2    3
#6187 3227  223 1277  now
#6189 3177  223 1282  previously
numericMeta.blood$alcohol_hx[numericMeta.blood.dirty$alcohol_hx>1]<-NA

hist(numericMeta.blood$total_years_smoked)
#numericMeta.blood$total_years_smoked[numericMeta.blood.dirty$total_years_smoked>80]<-NA

table(numericMeta.blood$tia)
#    0     1     2
#10433   255    54  now
#10449   256    54  previously
numericMeta.blood$tia[numericMeta.blood.dirty$tia>1]<-NA

table(numericMeta.blood$tbi)
#    0     1     2
#10286   536  2462  now
#10298   537  2421  previously
numericMeta.blood$tbi[numericMeta.blood.dirty$tbi>1]<-NA


table(numericMeta.blood$anxiety)
#    0     1     2
#11011  1297    90  now
#11023  1299    90  previously
numericMeta.blood$anxiety[numericMeta.blood.dirty$anxiety>1]<-NA


table(numericMeta.blood$APOE)
# 22   23   24   33   34   44
# 61 1587  379 8129 5055  890  now
# 62 1576  374 8106 5053  890  previously

numericMeta.blood$APOE4.Dose<-NA
numericMeta.blood$APOE4.Dose[as.numeric(numericMeta.blood$APOE)==22]<-0
numericMeta.blood$APOE4.Dose[as.numeric(numericMeta.blood$APOE)==23]<-0
numericMeta.blood$APOE4.Dose[as.numeric(numericMeta.blood$APOE)==24]<-1
numericMeta.blood$APOE4.Dose[as.numeric(numericMeta.blood$APOE)==33]<-0
numericMeta.blood$APOE4.Dose[as.numeric(numericMeta.blood$APOE)==34]<-1
numericMeta.blood$APOE4.Dose[as.numeric(numericMeta.blood$APOE)==44]<-2
table(numericMeta.blood$APOE4.Dose)
#   0    1    2
#9777 5434  890  now
#9744 5427  890  previously


#OK in CSF, but requiring cleaning in blood traits:
table(numericMeta.blood$mi)
#    0     1     2
#13113   745  2164  now
#13135   746  2164  previously
numericMeta.blood$mi[numericMeta.blood.dirty$mi>1]<-NA


table(numericMeta.blood$depression)
#    0     1     2
#13629  2183    37  now
#13651  2184    37  previously
numericMeta.blood$depression[numericMeta.blood.dirty$depression>1]<-NA

table(numericMeta.blood$stroke)
numericMeta.blood$stroke[numericMeta.blood.dirty$stroke>1]<-NA

table(numericMeta.blood$cancer)
numericMeta.blood$cancer[numericMeta.blood.dirty$cancer>1]<-NA

table(numericMeta.blood$diabetes)
numericMeta.blood$diabetes[numericMeta.blood.dirty$diabetes>1]<-NA

table(numericMeta.blood$chf) #congestive heart failure
numericMeta.blood$chf[numericMeta.blood.dirty$chf>1]<-NA

table(numericMeta.blood$copd)
numericMeta.blood$copd[numericMeta.blood.dirty$copd>1]<-NA

table(numericMeta.blood$afib)
numericMeta.blood$afib[numericMeta.blood.dirty$afib>1]<-NA

table(numericMeta.blood$angina)
numericMeta.blood$angina[numericMeta.blood.dirty$angina>1]<-NA

table(numericMeta.blood$hyperlipidaemia)
numericMeta.blood$hyperlipidaemia[numericMeta.blood.dirty$hyperlipidaemia>1]<-NA

table(numericMeta.blood$hypertension)
numericMeta.blood$hypertension[numericMeta.blood.dirty$hypertension>1]<-NA


###########################################################################
## New - Mapped 3 cohort traits from the 4 cohort Nat Aging curated traits

## UUID's sample_id, rownames, have changed -- remap
#UDS.map<-readRDS("UDS.map.RDS")
#RM.map<-readRDS("RM.map.RDS")
#BH.map<-readRDS("BH.map.RDS")

## ALL samples mapped previously are missing in v1.3ms HDS.
which(UDS.map[,1] %in% rownames(numericMeta.blood))
#integer(0)

#UDS.map<-UDS.map[which(UDS.map[,1] %in% rownames(numericMeta.blood)),]
#RM.map<-UDS.map[which(RM.map[,1] %in% rownames(numericMeta.blood)),]
#BH.map<-UDS.map[which(BH.map[,1] %in% rownames(numericMeta.blood)),]


######################
## Hungarian algorithm - minimize cost (-correlation, adjusted to min value 0) for all common, known rows


## Bio-Hermes ##

M2<-readRDS("ANML.BH.7289x1001.RDS")
M1<-exprMat0[,which(numericMeta$contributor_code=="A" & numericMeta$sample_type!="Calibrator" & numericMeta$is_somalogic==1)]

# NOTE - M2 named assays have @SYMBOL.(seqID.num); M1 has @seq.#####.###; Change assay namesp
rownames(M2)[which(grepl("@",rownames(M2)))] <- gsub("^(.*)\\|(.*)@\\1\\.(.*)$", "\\1\\|\\2@seq\\.\\3", rownames(M2)[which(grepl("@",rownames(M2)))])

# ------------------------------------------------------------------------
# ANNOTATION: Map BioHermes source sample identifiers back to GNPC/HDS
# sample IDs.
# ------------------------------------------------------------------------

commonRows<-intersect(rownames(M1),rownames(M2))
length(commonRows)
#7231


#library(lpSolve)

# Assume the following objects are defined:
# M1: matrix1 (log2(abundance)) with dimensions [n_assays x m1_samples]
# M2: matrix2 (log2(abundance)) with dimensions [n_assays x m2_samples]
# commonRows: vector of row indices (assays) to use (e.g. a set of >5000 rows known to be preserved)

# Step 1: Subset the matrices to the common assays.
M1_sub <- M1[commonRows, ]
M2_sub <- M2[commonRows, ]

# Step 2: Standardize each assay (row) to remove differences in overall normalization.
# This function computes z-scores across samples for each assay.
zscoreRows <- function(mat) {
  t(apply(mat, 1, function(x) {
    if (sd(x, na.rm=TRUE) > 0) {
      (x - mean(x, na.rm=TRUE)) / sd(x, na.rm=TRUE)
    } else {
      rep(0, length(x))
    }
  }))
}

M1_z <- zscoreRows(M1_sub)
M2_z <- zscoreRows(M2_sub)

# Step 3: Compute the correlation matrix between columns (samples) of M1 and M2.
# This yields a matrix of dimensions [m1_samples x m2_samples]
corrMat <- cor(M1_z, M2_z, use = "pairwise.complete.obs")

# Step 4: Create a cost matrix by taking the negative of the correlations.
# (We want to maximize correlation, so we minimize negative correlation.)
costMat <- -corrMat

# Step 5: Solve the assignment problem.
# Matrix1 has fewer samples than matrix2 (m1 < m2). We pad costMat to make it square.
m1 <- nrow(costMat)
m2 <- ncol(costMat)
if(m1 < m2){
  # Pad extra rows with a high cost so they are never selected.
  pad <- matrix(max(costMat, na.rm=TRUE) + 1, nrow = m2 - m1, ncol = m2)
  costMatPad <- rbind(costMat, pad)
} else {
  costMatPad <- costMat
}

# Solve the assignment problem using Hungarian algorithm implemented in C++, rather than lp.assign (slow linear programming):
assignment_sol <- clue::solve_LSAP(costMatPad+if(min(costMatPad)<0) { abs(min(costMatPad)) } else { 0 })  # slower:  #  lpSolve::lp.assign(costMatPad)$solution

# If lpSolve was used:
## Extract the solution for the real rows (matrix1 columns).
#assignment_mat <- assignment_sol[1:m1, , drop=FALSE]
#
## For each column of matrix1 (each row in the cost matrix), get the matched column in M2.
#matchIndex <- apply(assignment_mat, 1, function(x) which(x == 1))
#
## Step 6: Order the indices of matrix1 in the increasing order of the matched M2 sample indices.
## (This vector indicates the order of M1 columns most consistent with the M2 ordering.)
#sorted_M1_indices <- order(matchIndex)
#
## Output the result:
#sorted_M1_indices  # This vector gives the ordering of matrix1's columns.

## Output M2 ordered according to the optimal solution from clue::solve_LSAP(), and QC using bicor of all common rows.
M2.ordered_sub<-M2[commonRows, as.vector(assignment_sol)[1:ncol(M1)] ]

library(WGCNA)
commonRowBicors<-sapply(rownames(M1_sub),function(x) bicor(M1_sub[x,],M2.ordered_sub[x,], use='p'))
min(commonRowBicors)
#0.9919266

hist(commonRowBicors,breaks=25)
commonRowBicors.preOrderedM2<-sapply(rownames(M1_sub),function(x) bicor(M1_sub[x,],M2_sub[x,1:ncol(M1_sub)], use='p'))
#hist(commonRowBicors.preOrderedM2,fill="#BE999944", add=TRUE)
#--not seen in range of 0.95+
range(commonRowBicors.preOrderedM2)
#-0.1181119  0.4119755

# Reordering of M2 columns has allowed for large improvement in bicor of assay (row) values across samples -- from <0.5 to all assays > 0.94


BH.map=data.frame(SiteA.sample=colnames(M1), BH.sample=colnames(M2)[as.vector(assignment_sol)[1:ncol(M1)] ])
saveRDS(BH.map,"BH.map_HDS1.3ms.RDS")


## ROSMAP ##

M2<-readRDS("ANML.RM.7289x671.RDS")
M1<-exprMat0[,which(numericMeta$contributor_code=="R" & numericMeta$sample_type!="Calibrator" & numericMeta$is_somalogic==1)]

# NOTE - M2 named assays have @SYMBOL.(seqID.num); M1 has @seq.#####.###; Change assay namesp
rownames(M2)[which(grepl("@",rownames(M2)))] <- gsub("^(.*)\\|(.*)@\\1\\.(.*)$", "\\1\\|\\2@seq\\.\\3", rownames(M2)[which(grepl("@",rownames(M2)))])

commonRows<-intersect(rownames(M1),rownames(M2))

# ------------------------------------------------------------------------
# ANNOTATION: Map ROSMAP source sample identifiers back to GNPC/HDS sample
# IDs.
# ------------------------------------------------------------------------
length(commonRows)
#7231


#library(lpSolve)

# Assume the following objects are defined:
# M1: matrix1 (log2(abundance)) with dimensions [n_assays x m1_samples]
# M2: matrix2 (log2(abundance)) with dimensions [n_assays x m2_samples]
# commonRows: vector of row indices (assays) to use (e.g. a set of >5000 rows known to be preserved)

# Step 1: Subset the matrices to the common assays.
M1_sub <- M1[commonRows, ]
M2_sub <- M2[commonRows, ]

# Step 2: Standardize each assay (row) to remove differences in overall normalization.
# This function computes z-scores across samples for each assay.
zscoreRows <- function(mat) {
  t(apply(mat, 1, function(x) {
    if (sd(x, na.rm=TRUE) > 0) {
      (x - mean(x, na.rm=TRUE)) / sd(x, na.rm=TRUE)
    } else {
      rep(0, length(x))
    }
  }))
}

M1_z <- zscoreRows(M1_sub)
M2_z <- zscoreRows(M2_sub)

# Step 3: Compute the correlation matrix between columns (samples) of M1 and M2.
# This yields a matrix of dimensions [m1_samples x m2_samples]
corrMat <- cor(M1_z, M2_z, use = "pairwise.complete.obs")

# Step 4: Create a cost matrix by taking the negative of the correlations.
# (We want to maximize correlation, so we minimize negative correlation.)
costMat <- -corrMat

# Step 5: Solve the assignment problem.
# Matrix1 has fewer samples than matrix2 (m1 < m2). We pad costMat to make it square.
m1 <- nrow(costMat)
m2 <- ncol(costMat)
if(m1 < m2){
  # Pad extra rows with a high cost so they are never selected.
  pad <- matrix(max(costMat, na.rm=TRUE) + 1, nrow = m2 - m1, ncol = m2)
  costMatPad <- rbind(costMat, pad)
} else {
  costMatPad <- costMat
}

# Solve the assignment problem using Hungarian algorithm implemented in C++, rather than lp.assign (slow linear programming):
assignment_sol <- clue::solve_LSAP(costMatPad+if(min(costMatPad)<0) { abs(min(costMatPad)) } else { 0 })  # slower:  #  lpSolve::lp.assign(costMatPad)$solution

# If lpSolve was used:
## Extract the solution for the real rows (matrix1 columns).
#assignment_mat <- assignment_sol[1:m1, , drop=FALSE]
#
## For each column of matrix1 (each row in the cost matrix), get the matched column in M2.
#matchIndex <- apply(assignment_mat, 1, function(x) which(x == 1))
#
## Step 6: Order the indices of matrix1 in the increasing order of the matched M2 sample indices.
## (This vector indicates the order of M1 columns most consistent with the M2 ordering.)
#sorted_M1_indices <- order(matchIndex)
#
## Output the result:
#sorted_M1_indices  # This vector gives the ordering of matrix1's columns.

## Output M2 ordered according to the optimal solution from clue::solve_LSAP(), and QC using bicor of all common rows.
M2.ordered_sub<-M2[commonRows, as.vector(assignment_sol)[1:ncol(M1)] ]

library(WGCNA)
commonRowBicors<-sapply(rownames(M1_sub),function(x) bicor(M1_sub[x,],M2.ordered_sub[x,], use='p'))
min(commonRowBicors)
#0.9754976

hist(commonRowBicors,breaks=25)
commonRowBicors.preOrderedM2<-sapply(rownames(M1_sub),function(x) bicor(M1_sub[x,],M2_sub[x,1:ncol(M1_sub)], use='p'))
#hist(commonRowBicors.preOrderedM2,fill="#BE999944", add=TRUE)
#--not seen in range of 0.95+
range(commonRowBicors.preOrderedM2)
#-0.1226319  0.3012265

# Reordering of M2 columns has allowed for large improvement in bicor of assay (row) values across samples -- from <0.3 to all assays > 0.975


RM.map=data.frame(SiteR.sample=colnames(M1), RM.sample=colnames(M2)[as.vector(assignment_sol)[1:ncol(M1)] ])
saveRDS(RM.map,"RM.map_HDS1.3ms.RDS")


## UDS Emory ##

M2<-readRDS("ANML.UDS.7289x762.RDS")
M1<-exprMat0[,which(numericMeta$contributor_code=="D" & numericMeta$sample_type!="Calibrator" & numericMeta$is_somalogic==1)]

# NOTE - M2 named assays have @SYMBOL.(seqID.num); M1 has @seq.#####.###; Change assay namesp
rownames(M2)[which(grepl("@",rownames(M2)))] <- gsub("^(.*)\\|(.*)@\\1\\.(.*)$", "\\1\\|\\2@seq\\.\\3", rownames(M2)[which(grepl("@",rownames(M2)))])

commonRows<-intersect(rownames(M1),rownames(M2))
length(commonRows)
#7231

# ------------------------------------------------------------------------
# ANNOTATION: Map UDS source sample identifiers back to GNPC/HDS sample IDs.
# ------------------------------------------------------------------------


#library(lpSolve)

# Assume the following objects are defined:
# M1: matrix1 (log2(abundance)) with dimensions [n_assays x m1_samples]
# M2: matrix2 (log2(abundance)) with dimensions [n_assays x m2_samples]
# commonRows: vector of row indices (assays) to use (e.g. a set of >5000 rows known to be preserved)

# Step 1: Subset the matrices to the common assays.
M1_sub <- M1[commonRows, ]
M2_sub <- M2[commonRows, ]

# Step 2: Standardize each assay (row) to remove differences in overall normalization.
# This function computes z-scores across samples for each assay.
zscoreRows <- function(mat) {
  t(apply(mat, 1, function(x) {
    if (sd(x, na.rm=TRUE) > 0) {
      (x - mean(x, na.rm=TRUE)) / sd(x, na.rm=TRUE)
    } else {
      rep(0, length(x))
    }
  }))
}

M1_z <- zscoreRows(M1_sub)
M2_z <- zscoreRows(M2_sub)

# Step 3: Compute the correlation matrix between columns (samples) of M1 and M2.
# This yields a matrix of dimensions [m1_samples x m2_samples]
corrMat <- cor(M1_z, M2_z, use = "pairwise.complete.obs")

# Step 4: Create a cost matrix by taking the negative of the correlations.
# (We want to maximize correlation, so we minimize negative correlation.)
costMat <- -corrMat

# Step 5: Solve the assignment problem.
# Matrix1 has fewer samples than matrix2 (m1 < m2). We pad costMat to make it square.
m1 <- nrow(costMat)
m2 <- ncol(costMat)
if(m1 < m2){
  # Pad extra rows with a high cost so they are never selected.
  pad <- matrix(max(costMat, na.rm=TRUE) + 1, nrow = m2 - m1, ncol = m2)
  costMatPad <- rbind(costMat, pad)
} else {
  costMatPad <- costMat
}

# Solve the assignment problem using Hungarian algorithm implemented in C++, rather than lp.assign (slow linear programming):
assignment_sol <- clue::solve_LSAP(costMatPad+if(min(costMatPad)<0) { abs(min(costMatPad)) } else { 0 })  # slower:  #  lpSolve::lp.assign(costMatPad)$solution

# If lpSolve was used:
## Extract the solution for the real rows (matrix1 columns).
#assignment_mat <- assignment_sol[1:m1, , drop=FALSE]
#
## For each column of matrix1 (each row in the cost matrix), get the matched column in M2.
#matchIndex <- apply(assignment_mat, 1, function(x) which(x == 1))
#
## Step 6: Order the indices of matrix1 in the increasing order of the matched M2 sample indices.
## (This vector indicates the order of M1 columns most consistent with the M2 ordering.)
#sorted_M1_indices <- order(matchIndex)
#
## Output the result:
#sorted_M1_indices  # This vector gives the ordering of matrix1's columns.

## Output M2 ordered according to the optimal solution from clue::solve_LSAP(), and QC using bicor of all common rows.
M2.ordered_sub<-M2[commonRows, as.vector(assignment_sol)[1:ncol(M1)] ]

library(WGCNA)
commonRowBicors<-sapply(rownames(M1_sub),function(x) bicor(M1_sub[x,],M2.ordered_sub[x,], use='p'))
min(commonRowBicors)
# 1 now   previously 0.8697241

hist(commonRowBicors,breaks=25)
commonRowBicors.preOrderedM2<-sapply(rownames(M1_sub),function(x) bicor(M1_sub[x,],M2_sub[x,1:ncol(M1_sub)], use='p'))
#hist(commonRowBicors.preOrderedM2,fill="#BE999944", add=TRUE)
#--not seen in range of 0.95+
range(commonRowBicors.preOrderedM2)
#-0.1814513  0.3059096

# Reordering of M2 columns has allowed for large improvement in bicor of assay (row) values across samples -- from <0.3 to all assays > 0.975


UDS.map=data.frame(SiteD.sample=colnames(M1), UDS.sample=colnames(M2)[as.vector(assignment_sol)[1:ncol(M1)] ])
saveRDS(UDS.map,"UDS.map_HDS1.3ms.RDS")


############################################################################
## Pull in traits to mapped samples in the 3 cohorts BH (A), RM (R), UDS (D)

traits.4cohort<-read.csv(file="9b.4cohort.csv",row.names=1,header=TRUE, check.names=FALSE)

numericMeta.blood$Group.3mappedCohorts<-numericMeta.blood$Group
numericMeta.blood$Group.3mappedCohorts[match(UDS.map[,1],rownames(numericMeta.blood))]<-traits.4cohort$Group.pathCog[match(UDS.map[,2],traits.4cohort$LoadedSampleName)]
numericMeta.blood$Group.3mappedCohorts[match(BH.map[,1],rownames(numericMeta.blood))]<-traits.4cohort$Group.pathCog[match(BH.map[,2],traits.4cohort$LoadedSampleName)]
numericMeta.blood$Group.3mappedCohorts[match(RM.map[,1],rownames(numericMeta.blood))]<-traits.4cohort$Group[match(RM.map[,2],traits.4cohort$LoadedSampleName)]

table(numericMeta.blood$Group.3mappedCohorts)

# clean the off groups
numericMeta.blood$Group.3mappedCohorts[numericMeta.blood$Group.3mappedCohorts=="NA.MissingCogScore"]<-NA

# ------------------------------------------------------------------------
# ANNOTATION: Merge external four-cohort trait annotations and finalize
# derived diagnosis/covariate fields.
# ------------------------------------------------------------------------
numericMeta.blood$Group.3mappedCohorts[numericMeta.blood$Group.3mappedCohorts=="Normal"]<-"CT"
numericMeta.blood$Group.3mappedCohorts[numericMeta.blood$Group.3mappedCohorts=="Control"]<-"CT"
numericMeta.blood$Group.3mappedCohorts[numericMeta.blood$Group.3mappedCohorts=="OtherDementia"]<-"CI.Other"

table(numericMeta.blood$Group.3mappedCohorts)
#    AD      ALS   AsymAD CI.Other      CT     FTD     MCI      PD
#  1428      190      288      340    1783      78    1279    4861
#  1430      190      288      340    1783      78    1276    4865
sum(table(numericMeta.blood$Group.3mappedCohorts))
#10244 known diagnoses


numericMeta.blood$Group.pathCog.mapped<-NA
numericMeta.blood$Group.pathCog.mapped[match(UDS.map[,1],rownames(numericMeta.blood))]<-traits.4cohort$Group.pathCog[match(UDS.map[,2],traits.4cohort$LoadedSampleName)]
numericMeta.blood$Group.pathCog.mapped[match(BH.map[,1],rownames(numericMeta.blood))]<-traits.4cohort$Group.pathCog[match(BH.map[,2],traits.4cohort$LoadedSampleName)]

table(numericMeta.blood$Group.pathCog.mapped)

# clean the off group
numericMeta.blood$Group.pathCog.mapped[numericMeta.blood$Group.pathCog.mapped=="NA.MissingCogScore"]<-NA

table(numericMeta.blood$Group.pathCog.mapped)
#     AD   AsymAD CI.Other  Control
#    401      288      336      571
# did not change.


numericMeta.blood$Lilly.BH.blood.pTau217<-NA
numericMeta.blood$Lilly.BH.blood.pTau217[match(BH.map[,1],rownames(numericMeta.blood))]<-as.numeric(traits.4cohort$'Lilly Blood?\n\npTau217'[match(BH.map[,2],traits.4cohort$LoadedSampleName)])
Lilly.pTau217.temp<-traits.4cohort$'Lilly Blood?\n\npTau217'[match(BH.map[,2],traits.4cohort$LoadedSampleName)]
numericMeta.blood$Lilly.BH.blood.pTau217[match(BH.map[,1],rownames(numericMeta.blood))][which(Lilly.pTau217.temp=="<LLOQ")]<-min(numericMeta.blood$Lilly.BH.blood.pTau217,na.rm=T)/2
numericMeta.blood$Lilly.BH.blood.pTau217[match(BH.map[,1],rownames(numericMeta.blood))][which(Lilly.pTau217.temp==">ULOQ")]<-max(numericMeta.blood$Lilly.BH.blood.pTau217,na.rm=T)*1.5

numericMeta.blood$UDS.blood.pTau217<-NA
numericMeta.blood$UDS.blood.pTau217[match(UDS.map[,1],rownames(numericMeta.blood))]<-as.numeric(traits.4cohort$'UDS Plasma pTau217'[match(UDS.map[,2],traits.4cohort$LoadedSampleName)])


numericMeta.blood$AmyloidPositivity.withRM<-NA
numericMeta.blood$AmyloidPositivity.withRM[match(UDS.map[,1],rownames(numericMeta.blood))]<-traits.4cohort$AmyloidPositivity.withRM[match(UDS.map[,2],traits.4cohort$LoadedSampleName)]
numericMeta.blood$AmyloidPositivity.withRM[match(BH.map[,1],rownames(numericMeta.blood))]<-traits.4cohort$AmyloidPositivity.withRM[match(BH.map[,2],traits.4cohort$LoadedSampleName)]
numericMeta.blood$AmyloidPositivity.withRM[match(RM.map[,1],rownames(numericMeta.blood))]<-traits.4cohort$AmyloidPositivity.withRM[match(RM.map[,2],traits.4cohort$LoadedSampleName)]


numericMeta.blood$Group.withCTimputed<-numericMeta.blood$Group.3mappedCohorts  # previously, Group was used w/o 3 mapped cohort Dx Groups
numericMeta.blood$Group.withCTimputed[which(is.na(numericMeta.blood$Group.3mappedCohorts) & numericMeta.blood$cdr==0 & numericMeta.blood$MMSE>=28)]<-"CT"
table(numericMeta.blood$Group.withCTimputed)
#    AD      ALS   AsymAD CI.Other      CT     FTD     MCI      PD
#  1428      190      288      340    6831      78    1279    4861  # with CT imputation by cognition
#  1428      190      288      340    1783      78    1279    4861  # from above, without imputation of CT by cognition
sum(table(numericMeta.blood$Group.withCTimputed))
#15292 known diagnoses  -- 5048 imputed CT!


#now 6831 CT (previously 1156) ... vs 1428 AD, 12795 MCI, 4861 PD (unchanged)


## CSF specific
###############################################################################################################################################

#binary independent traits for ad, recruited_control (as defined in GNPClookup table) require a new strict Group (diagnosis) column definition:
table(paste0(numericMeta.CSF$ad,".",numericMeta.CSF$recruited_control))
# 0.0   0.2   1.0   1.2  NA.0 NA.NA    - #2=pending status, 1 YES, 0 NO (-1 -> NA)
#1244  1448    34   229   278   125

numericMeta.CSF$Group.AD.CT<-NA
numericMeta.CSF$Group.AD.CT[which(paste0(numericMeta.CSF$ad,".",numericMeta.CSF$recruited_control)=="1.0")]<-"AD"
numericMeta.CSF$Group.AD.CT[which(paste0(numericMeta.CSF$ad,".",numericMeta.CSF$recruited_control)=="1.2")]<-"AD"  # ad (1) favored over ct (pending, 2)
numericMeta.CSF$Group.AD.CT[which(paste0(numericMeta.CSF$ad,".",numericMeta.CSF$recruited_control)=="0.2")]<-"CT"  # pending ct, only available.
table(numericMeta.CSF$cdr[which(paste0(numericMeta.CSF$ad,".",numericMeta.CSF$recruited_control)=="NA.0")])
#  0 0.5   1
# 76  48   1  now  #unclear -- leave as NA
#124   x   1  prev #unclear -- leave as NA


table(numericMeta.CSF$Group.AD.CT)
#  AD   CT
# 263 1448  unchanged


table(paste0(numericMeta.CSF$mci_sci,".",numericMeta.CSF$recruited_control))
# 0.0   0.2   1.0   1.2  NA.0   NA.NA  - #2=pending status, 1 YES, 0 NO (-1 -> NA)
#1253  1290    25   387   278     125

numericMeta.CSF$Group.MCI.CT<-NA
numericMeta.CSF$Group.MCI.CT[which(paste0(numericMeta.CSF$mci_sci,".",numericMeta.CSF$recruited_control)=="1.0")]<-"MCI"
numericMeta.CSF$Group.MCI.CT[which(paste0(numericMeta.CSF$mci_sci,".",numericMeta.CSF$recruited_control)=="1.2")]<-"MCI"
numericMeta.CSF$Group.MCI.CT[which(paste0(numericMeta.CSF$mci_sci,".",numericMeta.CSF$recruited_control)=="0.2")]<-"CT"
table(numericMeta.CSF$Group.MCI.CT)
#  CT  MCI
#1290  412  unchanged


table(paste0(numericMeta.CSF$ftd,".",numericMeta.CSF$recruited_control))
# 0.0   0.2   1.0   1.2  NA.0 NA.NA    - #2=pending status, 1 YES, 0 NO (-1 -> NA)
#1280  1617     1    60   275   125

numericMeta.CSF$Group.FTD.CT<-NA
numericMeta.CSF$Group.FTD.CT[which(paste0(numericMeta.CSF$ftd,".",numericMeta.CSF$recruited_control)=="1.0")]<-"FTD"
numericMeta.CSF$Group.FTD.CT[which(paste0(numericMeta.CSF$ftd,".",numericMeta.CSF$recruited_control)=="1.2")]<-"FTD"
numericMeta.CSF$Group.FTD.CT[which(paste0(numericMeta.CSF$ftd,".",numericMeta.CSF$recruited_control)=="0.2")]<-"CT"
table(numericMeta.CSF$Group.FTD.CT)
#  CT  FTD
#1617   61  unchanged


table(paste0(numericMeta.CSF$pd,".",numericMeta.CSF$recruited_control))
# 0.0   0.2   1.0   1.2 NA.NA     - #2=pending status, 1 YES, 0 NO (-1 -> NA)
#1216  1622   340    55   125

numericMeta.CSF$Group.PD.CT<-NA
numericMeta.CSF$Group.PD.CT[which(paste0(numericMeta.CSF$pd,".",numericMeta.CSF$recruited_control)=="1.0")]<-"PD"
numericMeta.CSF$Group.PD.CT[which(paste0(numericMeta.CSF$pd,".",numericMeta.CSF$recruited_control)=="1.2")]<-"PD"
numericMeta.CSF$Group.PD.CT[which(paste0(numericMeta.CSF$pd,".",numericMeta.CSF$recruited_control)=="0.2")]<-"CT"
table(numericMeta.CSF$Group.PD.CT)
#  CT   PD
#1622  395  unchanged


table(paste0(numericMeta.CSF$als,".",numericMeta.CSF$recruited_control))
# 0.0   0.2   1.2  NA.0 NA.NA    - #2=pending status, 1 YES, 0 NO (-1 -> NA)
#1156  1671     6   400   125

numericMeta.CSF$Group.ALS.CT<-NA
#numericMeta.CSF$Group.ALS.CT[which(paste0(numericMeta.CSF$als,".",numericMeta.CSF$recruited_control)=="1.0")]<-"ALS"
numericMeta.CSF$Group.ALS.CT[which(paste0(numericMeta.CSF$als,".",numericMeta.CSF$recruited_control)=="1.2")]<-"ALS"
numericMeta.CSF$Group.ALS.CT[which(paste0(numericMeta.CSF$als,".",numericMeta.CSF$recruited_control)=="0.2")]<-"CT"
table(numericMeta.CSF$Group.ALS.CT)
# ALS   CT
#   6 1671  unchanged

#  Concatenate disease annotations in a new data frame column "numericMeta.CSF$Group", checking separate columns of the data frame numericMeta.CSF when more than one
# of the following columns have a value of "AD", "MCI", "FTD", "PD", and/or "ALS", and none of the columns have a value of "CT" in that row for any of these named columns of numericMeta.CSF:
# "Group.AD.CT", "Group.MCI.CT", "Group.FTD.CT", "Group.PD.CT", and "Group.ALS.CT".  Further, if only one disease annotation is found, set the Group column value for that row to the one disease annotation.
# Finally, if only "CT" is found in the checked columns, set the Group column value for that row to "CT".
cols <- c("Group.AD.CT", "Group.MCI.CT", "Group.FTD.CT", "Group.PD.CT", "Group.ALS.CT")  #  vector of colnames to check
numericMeta.CSF$Group <- apply(numericMeta.CSF[, cols], 1, function(x) {
  # Remove NA values
  x <- na.omit(x)

  # If no values, return NA
  if (length(x) == 0) return(NA)

  # If all values are "CT", then set Group to "CT"
  if (all(x == "CT")) return("CT")

  # Otherwise, remove any "CT" values and use the remaining disease annotations
  #x <- x[x != "CT"]

  # Get the unique annotations (should be one or more of: "AD", "MCI", "FTD", "PD", "ALS")
  x <- unique(x)

  # If there's only one annotation, return it; if more than one, concatenate them.
  if (length(x) == 1) {
    return(x)
  } else {
    return(paste(x, collapse = "."))
  }
})
table(numericMeta.CSF$Group)
#       AD    AD.CT  AD.CT.PD   AD.MCI       CT    CT.ALS     CT.FTD   CT.FTD.PD    CT.MCI   CT.MCI.PD   CT.PD     MCI    MCI.FTD    MCI.PD      PD
#       29      225         4        5      958        6          59           1       374          13      37      17          1         2     338  unchanged

numericMeta.CSF$GroupMulti<-numericMeta.CSF$Group
#numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="AD.FTD"]<-NA
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="AD.CT"]<-"AD"
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="AD.MCI"]<-"AD"
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="AD.MCI.PD"]<-NA
#numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="AD.PD"]<-NA
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="AD.CT.PD"]<-NA
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="CT.FTD.PD"]<-NA
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="CT.FTD"]<-"FTD"
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="CT.MCI"]<-"MCI"
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="CT.MCI.PD"]<-NA
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="CT.PD"]<-"PD"
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="FTD.PD"]<-NA
#numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="MCI.ALS"]<-"ALS"
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="MCI.FTD"]<-"FTD"
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="MCI.PD"]<-"PD"
numericMeta.CSF$Group[numericMeta.CSF$GroupMulti=="CT.ALS"]<-"ALS"

table(numericMeta.CSF$Group)
# AD ALS  CT FTD MCI  PD
#259   6 958  60 391 377  unchanged


###################################################################
## Clean Outliers/Typos in traits used for correlation

numericMeta.CSF.dirty<-numericMeta.CSF

# Traits to clean: "years_of_education","height_cm","weight_kg","resting_heart_rate_pulse","systolic_blood_pressure_sitting","diastolic_blood_pressure_sitting"
# (OK) "age_at_visit", "sex", "raceAA", "bmi", "cdr"

range(numericMeta.CSF$height_cm,na.rm=T)
#  0 198  now
hist(numericMeta.CSF$height_cm)
#numericMeta.CSF$height_cm[numericMeta.CSF.dirty$height_cm<100]<-NA

range(numericMeta.CSF$years_of_education,na.rm=T)
#  0 25  now
#numericMeta.CSF$years_of_education[numericMeta.CSF.dirty$years_of_education>35]<-NA

range(numericMeta.CSF$weight_kg,na.rm=T)
#  0.0 135.6  now
#numericMeta.CSF$weight_kg[numericMeta.CSF.dirty$weight_kg>400]<-NA
numericMeta.CSF$weight_kg[numericMeta.CSF.dirty$weight_kg==0]<-NA
range(numericMeta.CSF$weight_kg,na.rm=T)
# 36.9 135.6  now

range(numericMeta.CSF$bmi,na.rm=T)
#   14.2 53.0   now
hist(numericMeta.CSF$bmi)
#numericMeta.CSF$bmi[numericMeta.CSF.dirty$bmi>100]<-NA
#range(numericMeta.CSF$bmi,na.rm=T)
#

range(numericMeta.CSF$resting_heart_rate_pulse,na.rm=T)
#  42 253  now
#numericMeta.CSF$resting_heart_rate_pulse[numericMeta.CSF.dirty$resting_heart_rate_pulse>800]<-NA
##numericMeta.CSF$resting_heart_rate_pulse[numericMeta.CSF.dirty$resting_heart_rate_pulse==0]<-NA
hist(numericMeta.CSF$resting_heart_rate_pulse,breaks=20)
numericMeta.CSF$resting_heart_rate_pulse[numericMeta.CSF.dirty$resting_heart_rate_pulse>180]<-NA
#numericMeta.CSF$resting_heart_rate_pulse[numericMeta.CSF.dirty$resting_heart_rate_pulse<20]<-NA
range(numericMeta.CSF$resting_heart_rate_pulse,na.rm=T)
#  42 152  now

range(numericMeta.CSF$systolic_blood_pressure_sitting,na.rm=T)
#  63 195  now
#numericMeta.CSF$systolic_blood_pressure_sitting[numericMeta.CSF.dirty$systolic_blood_pressure_sitting>800]<-NA
#numericMeta.CSF$systolic_blood_pressure_sitting[numericMeta.CSF.dirty$systolic_blood_pressure_sitting==0]<-NA
#range(numericMeta.CSF$systolic_blood_pressure_sitting,na.rm=T)
hist(numericMeta.CSF$systolic_blood_pressure_sitting,breaks=40)
#numericMeta.CSF$systolic_blood_pressure_sitting[numericMeta.CSF.dirty$systolic_blood_pressure_sitting<50]<-NA
#range(numericMeta.CSF$systolic_blood_pressure_sitting,na.rm=T)

range(numericMeta.CSF$diastolic_blood_pressure_sitting,na.rm=T)
#  35 200  now
#numericMeta.CSF$diastolic_blood_pressure_sitting[numericMeta.CSF.dirty$diastolic_blood_pressure_sitting>800]<-NA
#numericMeta.CSF$diastolic_blood_pressure_sitting[numericMeta.CSF.dirty$diastolic_blood_pressure_sitting==0]<-NA
#range(numericMeta.CSF$diastolic_blood_pressure_sitting,na.rm=T)
hist(numericMeta.CSF$diastolic_blood_pressure_sitting)
numericMeta.CSF$diastolic_blood_pressure_sitting[numericMeta.CSF.dirty$diastolic_blood_pressure_sitting>150]<-NA


# More Traits to clean:  "alcohol_hx","total_years_smoked","tia","tbi","mi","depression","anxiety". "APOE4.Dose"
# (OK) "cdr","MMSE","MoCA","visit","sequential_visit_number","C9Orf72","GRN","MAPT",
# (OK, used indirectly; see below):  "recruited_control","ad","ftd","pd","als","mci_sci"

table(numericMeta.CSF$alcohol_hx)  # 0/1/2/3: Never/Current/Previous/Never_or_Previous
#   0    1    3
#1305  387   39  now
numericMeta.CSF$alcohol_hx[numericMeta.CSF.dirty$alcohol_hx>1]<-NA

hist(numericMeta.CSF$total_years_smoked)
#numericMeta.CSF$total_years_smoked[numericMeta.CSF.dirty$total_years_smoked>80]<-NA

table(numericMeta.CSF$tia)
#    0     1     2
# 1251    21     5  now
numericMeta.CSF$tia[numericMeta.CSF.dirty$tia>1]<-NA

table(numericMeta.CSF$tbi)
#    0     1     2
# 1257    10    10  now
numericMeta.CSF$tbi[numericMeta.CSF.dirty$tbi>1]<-NA


table(numericMeta.CSF$anxiety)
#    0     1     2
# 1131   265     4  now
numericMeta.CSF$anxiety[numericMeta.CSF.dirty$anxiety>1]<-NA


table(numericMeta.CSF$APOE)
# 22   23   24   33   34   44
#  4  110   25  809  375   60  now

numericMeta.CSF$APOE4.Dose<-NA
numericMeta.CSF$APOE4.Dose[as.numeric(numericMeta.CSF$APOE)==22]<-0
numericMeta.CSF$APOE4.Dose[as.numeric(numericMeta.CSF$APOE)==23]<-0
numericMeta.CSF$APOE4.Dose[as.numeric(numericMeta.CSF$APOE)==24]<-1
numericMeta.CSF$APOE4.Dose[as.numeric(numericMeta.CSF$APOE)==33]<-0
numericMeta.CSF$APOE4.Dose[as.numeric(numericMeta.CSF$APOE)==34]<-1
numericMeta.CSF$APOE4.Dose[as.numeric(numericMeta.CSF$APOE)==44]<-2
table(numericMeta.CSF$APOE4.Dose)
#   0    1    2
# 923  400    60  now


#OK in CSF, but requiring cleaning in blood traits:
table(numericMeta.CSF$mi)
#    0     1     2
#13113   745  2164  now
#13135   746  2164  previously
numericMeta.CSF$mi[numericMeta.CSF.dirty$mi>1]<-NA


table(numericMeta.CSF$depression)
#    0     1     2
# 1269     9     x  now
#numericMeta.CSF$depression[numericMeta.CSF.dirty$depression>1]<-NA

table(numericMeta.CSF$stroke)
numericMeta.CSF$stroke[numericMeta.CSF.dirty$stroke>1]<-NA

table(numericMeta.CSF$cancer)
numericMeta.CSF$cancer[numericMeta.CSF.dirty$cancer>1]<-NA

table(numericMeta.CSF$diabetes)
numericMeta.CSF$diabetes[numericMeta.CSF.dirty$diabetes>1]<-NA

table(numericMeta.CSF$chf) #congestive heart failure
numericMeta.CSF$chf[numericMeta.CSF.dirty$chf>1]<-NA

table(numericMeta.CSF$copd)
numericMeta.CSF$copd[numericMeta.CSF.dirty$copd>1]<-NA

table(numericMeta.CSF$afib)
numericMeta.CSF$afib[numericMeta.CSF.dirty$afib>1]<-NA

table(numericMeta.CSF$angina)
numericMeta.CSF$angina[numericMeta.CSF.dirty$angina>1]<-NA

table(numericMeta.CSF$hyperlipidaemia)
numericMeta.CSF$hyperlipidaemia[numericMeta.CSF.dirty$hyperlipidaemia>1]<-NA

table(numericMeta.CSF$hypertension)
numericMeta.CSF$hypertension[numericMeta.CSF.dirty$hypertension>1]<-NA


# Save Memory for RData, removing unneeded variables:
rm(list=c("commonRowBicors","commonRowBicors.preOrderedM2","commonRows","corrMat","costMat","costMatPad","exprMat.log2Subset","exprMat.unlogSubset","m1","M1","M1_sub","M1_z","m2","M2","M2.ordered_sub","M2_sub","M2_z","minus1.count","pad"))
rm(list=c("exprMat0.all")) #non-human analytes will not be used in downstream analysis. Save RAM.

## COMPLETELY CLEAN AND IMPUTED TRAITS ARE IN numericMeta.CSF and numericMeta.blood (exprMat0 not yet split to save RAM)
save.image("2.saved.image_trait+human_cleanup_nm+em0_V1_3ms_03-27-25.RData")


## Missed: 24 samples in plasma have MMSE>30 (96-98)
numericMeta.blood$MMSE[which(numericMeta.blood$MMSE>30)]<-NA

# Check and clean CSF as well
length(which(numericMeta.CSF$MMSE>30))
#
numericMeta.CSF$MMSE[which(numericMeta.CSF$MMSE>30)]<-NA
